'use client';
import { useRouter } from 'next/navigation';
import { useState, type FormEvent } from 'react';
import Chart from './chart';
type Holding={ticker:string;kind:'stock'|'crypto';quantity:string;close:string|null;priceDate:string|null;value:string|null};
type Point={date:string;value:number};
type ApiBody={error?:string;status?:string;date?:string;market_value?:string;reason?:string};
export default function Dashboard({holdings,history}:{holdings:Holding[];history:Point[]}) {
 const router=useRouter(); const [kind,setKind]=useState<'stock'|'crypto'>('stock'),[action,setAction]=useState('BUY'),[ticker,setTicker]=useState(''),[quantity,setQuantity]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const last=history.at(-1),prev=history.at(-2),change=last&&prev?last.value-prev.value:null;
 const money=(value:number)=>value.toLocaleString('en-US',{style:'currency',currency:'USD'});
 async function syncNow() {
  setBusy(true);setMessage('');
  try { const response=await fetch('/api/admin/sync',{method:'POST'});const body=await response.json() as ApiBody; if(!response.ok) throw new Error(body.error??'同步失败');setMessage(body.status==='synced'?`价格已更新：${body.date}，净值 ${money(Number(body.market_value))}`:body.reason??'没有新数据');router.refresh(); }
  catch(error) {setMessage(error instanceof Error?error.message:'同步失败');}finally{setBusy(false);}
 }
 async function add(event:FormEvent) {
  event.preventDefault();setBusy(true);setMessage('');
  try {const response=await fetch('/api/transactions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,action,ticker,quantity,date})});const body=await response.json() as ApiBody;if(!response.ok)throw new Error(body.error??'保存失败');setTicker('');setQuantity('');setMessage('交易已保存。点击“同步最新价格”更新净值。');router.refresh();}
  catch(error) {setMessage(error instanceof Error?error.message:'保存失败');}finally{setBusy(false);}
 }
 async function logout() { await fetch('/api/auth',{method:'DELETE'});router.refresh(); }
 return <main className="mx-auto max-w-6xl px-5 py-8 md:px-10"><header className="mb-9 flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.3em] text-teal-700">Personal portfolio</p><h1 className="mt-2 text-3xl font-bold">净值总览</h1></div><button onClick={logout} className="rounded-xl border border-slate-300 px-4 py-2 text-sm">退出登录</button></header>
 <div className="grid gap-5 md:grid-cols-3"><section className="rounded-2xl bg-slate-950 p-6 text-white md:col-span-2"><p className="text-sm text-slate-300">最近一次记录的净值 · {last?.date??'等待首次同步'}</p><p className="mt-4 text-4xl font-semibold">{last?money(last.value):'—'}</p><p className="mt-3 text-sm text-slate-300">{change===null?'添加持仓并同步价格后开始记录变化':`较上一记录 ${change>=0?'+':''}${money(change)}`}</p></section><section className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">持仓资产</p><p className="mt-3 text-4xl font-semibold">{holdings.length}</p><button disabled={busy} onClick={syncNow} className="mt-5 w-full rounded-xl bg-teal-700 px-4 py-3 font-medium text-white disabled:opacity-50">{busy?'正在处理…':'同步最新价格'}</button></section></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-baseline justify-between"><h2 className="text-xl font-semibold">净值变化</h2><span className="text-xs text-slate-500">USD · 每日收盘价</span></div>{history.length?<Chart data={history}/>:<div className="grid h-80 place-items-center text-center text-slate-500">暂无净值记录。添加持仓后同步价格即可开始绘图。</div>}</section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">添加交易</h2><p className="mt-1 text-sm text-slate-500">输入交易日期和数量；卖出会减少持仓。</p><form onSubmit={add} className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3"><label className="text-sm">类别<select value={kind} onChange={e=>{setKind(e.target.value as 'stock'|'crypto');setTicker('');}} className="mt-1 w-full rounded-xl border p-3"><option value="stock">股票 / ETF</option><option value="crypto">加密货币</option></select></label><label className="text-sm">操作<select value={action} onChange={e=>setAction(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="BUY">买入 / 增加</option><option value="SELL">卖出 / 减少</option></select></label></div><label className="block text-sm">{kind==='crypto'?'交易对（如 BTC/USD）':'股票代码（如 AAPL）'}<input required value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder={kind==='crypto'?'BTC/USD':'AAPL'} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm">数量（unit）<input required type="number" min="0.000000000001" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm">交易日期<input required type="date" max={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><button disabled={busy} className="w-full rounded-xl bg-slate-900 px-4 py-3 font-medium text-white disabled:opacity-50">保存交易</button></form></section></div>
 <section className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">当前持仓</h2>{holdings.length?<div className="mt-4 divide-y">{holdings.map(h=><div key={h.ticker} className="grid grid-cols-2 gap-2 py-4 text-sm md:grid-cols-4"><div><span className="font-semibold">{h.ticker}</span><p className="text-slate-500">{h.kind==='crypto'?'Crypto':'Stock'}</p></div><div><p className="text-slate-500">数量</p><p>{h.quantity}</p></div><div><p className="text-slate-500">最近收盘价</p><p>{h.close?`${money(Number(h.close))} · ${h.priceDate}`:'等待同步'}</p></div><div><p className="text-slate-500">估算市值</p><p className="font-semibold">{h.value?money(Number(h.value)):'—'}</p></div></div>)}</div>:<p className="mt-4 text-slate-500">暂无持仓。在右侧添加股票或加密货币。</p>}</section>{message&&<p role="status" className="mt-5 rounded-xl bg-teal-50 p-4 text-sm text-teal-900">{message}</p>}<p className="mt-6 text-xs text-slate-500">股票使用最近交易日收盘价；加密货币使用已完成的 UTC 日线。净值不含现金、费用和股息。历史曲线会随每日同步累积。</p></main>;
}
